{
 "title": "DNS",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CoreDNS Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "date"
    },
    {
     "alias": "DNSSEC",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "dnssec:true",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Unbound Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "date"
    },
    {
     "alias": "DNSSEC",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "dnssec:true",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Avg. Response Time",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "duration",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "code",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "server",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "SERVFAIL",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "code:\"SERVFAIL\"",
     "timeField": "date"
    },
    {
     "alias": "NXDOMAIN",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "code:\"NXDOMAIN\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "type",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Old DNS Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "remote:\"10.0.0.3\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Domains",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "remote",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "DNSSEC Domains",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "dnssec:true",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Insecure Domains",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "dnssec:false",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "CoreDNS Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Unbound Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "timeField": "date"
    }
   ]
  }
 ]
}